#!/usr/bin/env bash

# ARG1: theme  [blue, white etc]
# ARG2: brightness [0-255]

# cron doesn't run in interactive so we need to source a profile
# for the PARTICLE_TOKEN API key but bashrc won't work on debian with cron
source ~/.profile

if [ -z "$1" ]; then
  theme="white"
else
  theme=$1
fi

if [ -z "$2" ]; then
  brightness="60"
else
  brightness=$2
fi

moviestatus=`curl -s "https://api.particle.io/v1/devices/<device id of control node>/movietime?access_token=${PARTICLE_TOKEN}" | jq .result`

if [[ ${moviestatus} == 1 ]]; then
  exit
fi

if [ "$theme" = "off" ]; then
  curl -s https://api.particle.io/v1/devices/events -d private=true -d name=squarism/blinkwon -d data='{"theme":"off"}' -d access_token=${PARTICLE_TOKEN} > /dev/null
else
  curl -s https://api.particle.io/v1/devices/events \
    -d private=true \
    -d name=squarism/blinkwon \
    -d data='{"brightness":'"${brightness}"',"theme":"'${theme}'"}' \
    -d access_token=${PARTICLE_TOKEN} \
    > /dev/null
fi

exit && exit
